// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CGGetDayTaskRewardMsg.proto

package buffer;

public final class CGGetDayTaskRewardMsg {
  private CGGetDayTaskRewardMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CGGetDayTaskRewardProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 msgType = 1 [default = 2211];
    boolean hasMsgType();
    int getMsgType();
    
    // optional int32 rewardType = 2;
    boolean hasRewardType();
    int getRewardType();
    
    // optional int32 activeId = 3;
    boolean hasActiveId();
    int getActiveId();
    
    // optional int32 taskId = 4;
    boolean hasTaskId();
    int getTaskId();
  }
  public static final class CGGetDayTaskRewardProto extends
      com.google.protobuf.GeneratedMessage
      implements CGGetDayTaskRewardProtoOrBuilder {
    // Use CGGetDayTaskRewardProto.newBuilder() to construct.
    private CGGetDayTaskRewardProto(Builder builder) {
      super(builder);
    }
    private CGGetDayTaskRewardProto(boolean noInit) {}
    
    private static final CGGetDayTaskRewardProto defaultInstance;
    public static CGGetDayTaskRewardProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public CGGetDayTaskRewardProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffer.CGGetDayTaskRewardMsg.internal_static_buffer_CGGetDayTaskRewardProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffer.CGGetDayTaskRewardMsg.internal_static_buffer_CGGetDayTaskRewardProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 msgType = 1 [default = 2211];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional int32 rewardType = 2;
    public static final int REWARDTYPE_FIELD_NUMBER = 2;
    private int rewardType_;
    public boolean hasRewardType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRewardType() {
      return rewardType_;
    }
    
    // optional int32 activeId = 3;
    public static final int ACTIVEID_FIELD_NUMBER = 3;
    private int activeId_;
    public boolean hasActiveId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getActiveId() {
      return activeId_;
    }
    
    // optional int32 taskId = 4;
    public static final int TASKID_FIELD_NUMBER = 4;
    private int taskId_;
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getTaskId() {
      return taskId_;
    }
    
    private void initFields() {
      msgType_ = 2211;
      rewardType_ = 0;
      activeId_ = 0;
      taskId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rewardType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, activeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, taskId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rewardType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, activeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, taskId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffer.CGGetDayTaskRewardMsg.internal_static_buffer_CGGetDayTaskRewardProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffer.CGGetDayTaskRewardMsg.internal_static_buffer_CGGetDayTaskRewardProto_fieldAccessorTable;
      }
      
      // Construct using buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = 2211;
        bitField0_ = (bitField0_ & ~0x00000001);
        rewardType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        activeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto.getDescriptor();
      }
      
      public buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto getDefaultInstanceForType() {
        return buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto.getDefaultInstance();
      }
      
      public buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto build() {
        buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto buildPartial() {
        buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto result = new buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rewardType_ = rewardType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.activeId_ = activeId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto) {
          return mergeFrom((buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto other) {
        if (other == buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasRewardType()) {
          setRewardType(other.getRewardType());
        }
        if (other.hasActiveId()) {
          setActiveId(other.getActiveId());
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rewardType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              activeId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              taskId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 msgType = 1 [default = 2211];
      private int msgType_ = 2211;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 2211;
        onChanged();
        return this;
      }
      
      // optional int32 rewardType = 2;
      private int rewardType_ ;
      public boolean hasRewardType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRewardType() {
        return rewardType_;
      }
      public Builder setRewardType(int value) {
        bitField0_ |= 0x00000002;
        rewardType_ = value;
        onChanged();
        return this;
      }
      public Builder clearRewardType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rewardType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 activeId = 3;
      private int activeId_ ;
      public boolean hasActiveId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getActiveId() {
        return activeId_;
      }
      public Builder setActiveId(int value) {
        bitField0_ |= 0x00000004;
        activeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearActiveId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        activeId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 taskId = 4;
      private int taskId_ ;
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getTaskId() {
        return taskId_;
      }
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000008;
        taskId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        taskId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:buffer.CGGetDayTaskRewardProto)
    }
    
    static {
      defaultInstance = new CGGetDayTaskRewardProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buffer.CGGetDayTaskRewardProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buffer_CGGetDayTaskRewardProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buffer_CGGetDayTaskRewardProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CGGetDayTaskRewardMsg.proto\022\006buffer\"f\n" +
      "\027CGGetDayTaskRewardProto\022\025\n\007msgType\030\001 \001(" +
      "\005:\0042211\022\022\n\nrewardType\030\002 \001(\005\022\020\n\010activeId\030" +
      "\003 \001(\005\022\016\n\006taskId\030\004 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_buffer_CGGetDayTaskRewardProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_buffer_CGGetDayTaskRewardProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buffer_CGGetDayTaskRewardProto_descriptor,
              new java.lang.String[] { "MsgType", "RewardType", "ActiveId", "TaskId", },
              buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto.class,
              buffer.CGGetDayTaskRewardMsg.CGGetDayTaskRewardProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
