// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CGMailReadMsg.proto

package buffer;

public final class CGMailReadMsg {
  private CGMailReadMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CGMailReadProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 msgType = 1 [default = 2202];
    boolean hasMsgType();
    int getMsgType();
    
    // optional int32 readType = 2;
    boolean hasReadType();
    int getReadType();
    
    // optional int32 mailType = 3;
    boolean hasMailType();
    int getMailType();
    
    // optional int64 params = 4;
    boolean hasParams();
    long getParams();
  }
  public static final class CGMailReadProto extends
      com.google.protobuf.GeneratedMessage
      implements CGMailReadProtoOrBuilder {
    // Use CGMailReadProto.newBuilder() to construct.
    private CGMailReadProto(Builder builder) {
      super(builder);
    }
    private CGMailReadProto(boolean noInit) {}
    
    private static final CGMailReadProto defaultInstance;
    public static CGMailReadProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public CGMailReadProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffer.CGMailReadMsg.internal_static_buffer_CGMailReadProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffer.CGMailReadMsg.internal_static_buffer_CGMailReadProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 msgType = 1 [default = 2202];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional int32 readType = 2;
    public static final int READTYPE_FIELD_NUMBER = 2;
    private int readType_;
    public boolean hasReadType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getReadType() {
      return readType_;
    }
    
    // optional int32 mailType = 3;
    public static final int MAILTYPE_FIELD_NUMBER = 3;
    private int mailType_;
    public boolean hasMailType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getMailType() {
      return mailType_;
    }
    
    // optional int64 params = 4;
    public static final int PARAMS_FIELD_NUMBER = 4;
    private long params_;
    public boolean hasParams() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getParams() {
      return params_;
    }
    
    private void initFields() {
      msgType_ = 2202;
      readType_ = 0;
      mailType_ = 0;
      params_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, readType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, mailType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, params_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, readType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, mailType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, params_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.CGMailReadMsg.CGMailReadProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffer.CGMailReadMsg.CGMailReadProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements buffer.CGMailReadMsg.CGMailReadProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffer.CGMailReadMsg.internal_static_buffer_CGMailReadProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffer.CGMailReadMsg.internal_static_buffer_CGMailReadProto_fieldAccessorTable;
      }
      
      // Construct using buffer.CGMailReadMsg.CGMailReadProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = 2202;
        bitField0_ = (bitField0_ & ~0x00000001);
        readType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        mailType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffer.CGMailReadMsg.CGMailReadProto.getDescriptor();
      }
      
      public buffer.CGMailReadMsg.CGMailReadProto getDefaultInstanceForType() {
        return buffer.CGMailReadMsg.CGMailReadProto.getDefaultInstance();
      }
      
      public buffer.CGMailReadMsg.CGMailReadProto build() {
        buffer.CGMailReadMsg.CGMailReadProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private buffer.CGMailReadMsg.CGMailReadProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        buffer.CGMailReadMsg.CGMailReadProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public buffer.CGMailReadMsg.CGMailReadProto buildPartial() {
        buffer.CGMailReadMsg.CGMailReadProto result = new buffer.CGMailReadMsg.CGMailReadProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.readType_ = readType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mailType_ = mailType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffer.CGMailReadMsg.CGMailReadProto) {
          return mergeFrom((buffer.CGMailReadMsg.CGMailReadProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(buffer.CGMailReadMsg.CGMailReadProto other) {
        if (other == buffer.CGMailReadMsg.CGMailReadProto.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasReadType()) {
          setReadType(other.getReadType());
        }
        if (other.hasMailType()) {
          setMailType(other.getMailType());
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              readType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              mailType_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              params_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 msgType = 1 [default = 2202];
      private int msgType_ = 2202;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 2202;
        onChanged();
        return this;
      }
      
      // optional int32 readType = 2;
      private int readType_ ;
      public boolean hasReadType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getReadType() {
        return readType_;
      }
      public Builder setReadType(int value) {
        bitField0_ |= 0x00000002;
        readType_ = value;
        onChanged();
        return this;
      }
      public Builder clearReadType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        readType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 mailType = 3;
      private int mailType_ ;
      public boolean hasMailType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getMailType() {
        return mailType_;
      }
      public Builder setMailType(int value) {
        bitField0_ |= 0x00000004;
        mailType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMailType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mailType_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 params = 4;
      private long params_ ;
      public boolean hasParams() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getParams() {
        return params_;
      }
      public Builder setParams(long value) {
        bitField0_ |= 0x00000008;
        params_ = value;
        onChanged();
        return this;
      }
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000008);
        params_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:buffer.CGMailReadProto)
    }
    
    static {
      defaultInstance = new CGMailReadProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buffer.CGMailReadProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buffer_CGMailReadProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buffer_CGMailReadProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CGMailReadMsg.proto\022\006buffer\"\\\n\017CGMailR" +
      "eadProto\022\025\n\007msgType\030\001 \001(\005:\0042202\022\020\n\010readT" +
      "ype\030\002 \001(\005\022\020\n\010mailType\030\003 \001(\005\022\016\n\006params\030\004 " +
      "\001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_buffer_CGMailReadProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_buffer_CGMailReadProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buffer_CGMailReadProto_descriptor,
              new java.lang.String[] { "MsgType", "ReadType", "MailType", "Params", },
              buffer.CGMailReadMsg.CGMailReadProto.class,
              buffer.CGMailReadMsg.CGMailReadProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
