// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GCFunctionOpenInfoMsg.proto

package buffer;

public final class GCFunctionOpenInfoMsg {
  private GCFunctionOpenInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GCFunctionOpenInfoProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 msgType = 1 [default = 5509];
    boolean hasMsgType();
    int getMsgType();
    
    // optional int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // repeated int32 functionIds = 3;
    java.util.List<java.lang.Integer> getFunctionIdsList();
    int getFunctionIdsCount();
    int getFunctionIds(int index);
  }
  public static final class GCFunctionOpenInfoProto extends
      com.google.protobuf.GeneratedMessage
      implements GCFunctionOpenInfoProtoOrBuilder {
    // Use GCFunctionOpenInfoProto.newBuilder() to construct.
    private GCFunctionOpenInfoProto(Builder builder) {
      super(builder);
    }
    private GCFunctionOpenInfoProto(boolean noInit) {}
    
    private static final GCFunctionOpenInfoProto defaultInstance;
    public static GCFunctionOpenInfoProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public GCFunctionOpenInfoProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffer.GCFunctionOpenInfoMsg.internal_static_buffer_GCFunctionOpenInfoProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffer.GCFunctionOpenInfoMsg.internal_static_buffer_GCFunctionOpenInfoProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 msgType = 1 [default = 5509];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // repeated int32 functionIds = 3;
    public static final int FUNCTIONIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> functionIds_;
    public java.util.List<java.lang.Integer>
        getFunctionIdsList() {
      return functionIds_;
    }
    public int getFunctionIdsCount() {
      return functionIds_.size();
    }
    public int getFunctionIds(int index) {
      return functionIds_.get(index);
    }
    
    private void initFields() {
      msgType_ = 5509;
      status_ = 0;
      functionIds_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      for (int i = 0; i < functionIds_.size(); i++) {
        output.writeInt32(3, functionIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < functionIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(functionIds_.get(i));
        }
        size += dataSize;
        size += 1 * getFunctionIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffer.GCFunctionOpenInfoMsg.internal_static_buffer_GCFunctionOpenInfoProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffer.GCFunctionOpenInfoMsg.internal_static_buffer_GCFunctionOpenInfoProto_fieldAccessorTable;
      }
      
      // Construct using buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = 5509;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        functionIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto.getDescriptor();
      }
      
      public buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto getDefaultInstanceForType() {
        return buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto.getDefaultInstance();
      }
      
      public buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto build() {
        buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto buildPartial() {
        buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto result = new buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          functionIds_ = java.util.Collections.unmodifiableList(functionIds_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.functionIds_ = functionIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto) {
          return mergeFrom((buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto other) {
        if (other == buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (!other.functionIds_.isEmpty()) {
          if (functionIds_.isEmpty()) {
            functionIds_ = other.functionIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFunctionIdsIsMutable();
            functionIds_.addAll(other.functionIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              ensureFunctionIdsIsMutable();
              functionIds_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addFunctionIds(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 msgType = 1 [default = 5509];
      private int msgType_ = 5509;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 5509;
        onChanged();
        return this;
      }
      
      // optional int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // repeated int32 functionIds = 3;
      private java.util.List<java.lang.Integer> functionIds_ = java.util.Collections.emptyList();;
      private void ensureFunctionIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          functionIds_ = new java.util.ArrayList<java.lang.Integer>(functionIds_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<java.lang.Integer>
          getFunctionIdsList() {
        return java.util.Collections.unmodifiableList(functionIds_);
      }
      public int getFunctionIdsCount() {
        return functionIds_.size();
      }
      public int getFunctionIds(int index) {
        return functionIds_.get(index);
      }
      public Builder setFunctionIds(
          int index, int value) {
        ensureFunctionIdsIsMutable();
        functionIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFunctionIds(int value) {
        ensureFunctionIdsIsMutable();
        functionIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFunctionIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFunctionIdsIsMutable();
        super.addAll(values, functionIds_);
        onChanged();
        return this;
      }
      public Builder clearFunctionIds() {
        functionIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:buffer.GCFunctionOpenInfoProto)
    }
    
    static {
      defaultInstance = new GCFunctionOpenInfoProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buffer.GCFunctionOpenInfoProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buffer_GCFunctionOpenInfoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buffer_GCFunctionOpenInfoProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033GCFunctionOpenInfoMsg.proto\022\006buffer\"U\n" +
      "\027GCFunctionOpenInfoProto\022\025\n\007msgType\030\001 \001(" +
      "\005:\0045509\022\016\n\006status\030\002 \001(\005\022\023\n\013functionIds\030\003" +
      " \003(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_buffer_GCFunctionOpenInfoProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_buffer_GCFunctionOpenInfoProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buffer_GCFunctionOpenInfoProto_descriptor,
              new java.lang.String[] { "MsgType", "Status", "FunctionIds", },
              buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto.class,
              buffer.GCFunctionOpenInfoMsg.GCFunctionOpenInfoProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
