// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GCGetLuckDrawInfoMsg.proto

package buffer;

public final class GCGetLuckDrawInfoMsg {
  private GCGetLuckDrawInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GCGetLuckDrawInfoProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 msgType = 1 [default = 3316];
    boolean hasMsgType();
    int getMsgType();
    
    // optional int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // optional int32 luckNum = 3;
    boolean hasLuckNum();
    int getLuckNum();
    
    // optional int64 nextFreeTime = 4;
    boolean hasNextFreeTime();
    long getNextFreeTime();
    
    // optional int32 maxLuckNum = 5;
    boolean hasMaxLuckNum();
    int getMaxLuckNum();
    
    // optional string cost = 6;
    boolean hasCost();
    String getCost();
    
    // optional int32 luckDrawNum = 7;
    boolean hasLuckDrawNum();
    int getLuckDrawNum();
  }
  public static final class GCGetLuckDrawInfoProto extends
      com.google.protobuf.GeneratedMessage
      implements GCGetLuckDrawInfoProtoOrBuilder {
    // Use GCGetLuckDrawInfoProto.newBuilder() to construct.
    private GCGetLuckDrawInfoProto(Builder builder) {
      super(builder);
    }
    private GCGetLuckDrawInfoProto(boolean noInit) {}
    
    private static final GCGetLuckDrawInfoProto defaultInstance;
    public static GCGetLuckDrawInfoProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public GCGetLuckDrawInfoProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffer.GCGetLuckDrawInfoMsg.internal_static_buffer_GCGetLuckDrawInfoProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffer.GCGetLuckDrawInfoMsg.internal_static_buffer_GCGetLuckDrawInfoProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 msgType = 1 [default = 3316];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional int32 luckNum = 3;
    public static final int LUCKNUM_FIELD_NUMBER = 3;
    private int luckNum_;
    public boolean hasLuckNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLuckNum() {
      return luckNum_;
    }
    
    // optional int64 nextFreeTime = 4;
    public static final int NEXTFREETIME_FIELD_NUMBER = 4;
    private long nextFreeTime_;
    public boolean hasNextFreeTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getNextFreeTime() {
      return nextFreeTime_;
    }
    
    // optional int32 maxLuckNum = 5;
    public static final int MAXLUCKNUM_FIELD_NUMBER = 5;
    private int maxLuckNum_;
    public boolean hasMaxLuckNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getMaxLuckNum() {
      return maxLuckNum_;
    }
    
    // optional string cost = 6;
    public static final int COST_FIELD_NUMBER = 6;
    private java.lang.Object cost_;
    public boolean hasCost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getCost() {
      java.lang.Object ref = cost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cost_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCostBytes() {
      java.lang.Object ref = cost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 luckDrawNum = 7;
    public static final int LUCKDRAWNUM_FIELD_NUMBER = 7;
    private int luckDrawNum_;
    public boolean hasLuckDrawNum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getLuckDrawNum() {
      return luckDrawNum_;
    }
    
    private void initFields() {
      msgType_ = 3316;
      status_ = 0;
      luckNum_ = 0;
      nextFreeTime_ = 0L;
      maxLuckNum_ = 0;
      cost_ = "";
      luckDrawNum_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, luckNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, nextFreeTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, maxLuckNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, luckDrawNum_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, luckNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, nextFreeTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, maxLuckNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCostBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, luckDrawNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffer.GCGetLuckDrawInfoMsg.internal_static_buffer_GCGetLuckDrawInfoProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffer.GCGetLuckDrawInfoMsg.internal_static_buffer_GCGetLuckDrawInfoProto_fieldAccessorTable;
      }
      
      // Construct using buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = 3316;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        luckNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        nextFreeTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        maxLuckNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        cost_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        luckDrawNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto.getDescriptor();
      }
      
      public buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto getDefaultInstanceForType() {
        return buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto.getDefaultInstance();
      }
      
      public buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto build() {
        buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto buildPartial() {
        buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto result = new buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.luckNum_ = luckNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nextFreeTime_ = nextFreeTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.maxLuckNum_ = maxLuckNum_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.cost_ = cost_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.luckDrawNum_ = luckDrawNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto) {
          return mergeFrom((buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto other) {
        if (other == buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasLuckNum()) {
          setLuckNum(other.getLuckNum());
        }
        if (other.hasNextFreeTime()) {
          setNextFreeTime(other.getNextFreeTime());
        }
        if (other.hasMaxLuckNum()) {
          setMaxLuckNum(other.getMaxLuckNum());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        if (other.hasLuckDrawNum()) {
          setLuckDrawNum(other.getLuckDrawNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              luckNum_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              nextFreeTime_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              maxLuckNum_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              cost_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              luckDrawNum_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 msgType = 1 [default = 3316];
      private int msgType_ = 3316;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 3316;
        onChanged();
        return this;
      }
      
      // optional int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 luckNum = 3;
      private int luckNum_ ;
      public boolean hasLuckNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLuckNum() {
        return luckNum_;
      }
      public Builder setLuckNum(int value) {
        bitField0_ |= 0x00000004;
        luckNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearLuckNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        luckNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 nextFreeTime = 4;
      private long nextFreeTime_ ;
      public boolean hasNextFreeTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getNextFreeTime() {
        return nextFreeTime_;
      }
      public Builder setNextFreeTime(long value) {
        bitField0_ |= 0x00000008;
        nextFreeTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearNextFreeTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nextFreeTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 maxLuckNum = 5;
      private int maxLuckNum_ ;
      public boolean hasMaxLuckNum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getMaxLuckNum() {
        return maxLuckNum_;
      }
      public Builder setMaxLuckNum(int value) {
        bitField0_ |= 0x00000010;
        maxLuckNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxLuckNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        maxLuckNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional string cost = 6;
      private java.lang.Object cost_ = "";
      public boolean hasCost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getCost() {
        java.lang.Object ref = cost_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCost(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        cost_ = value;
        onChanged();
        return this;
      }
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cost_ = getDefaultInstance().getCost();
        onChanged();
        return this;
      }
      void setCost(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        cost_ = value;
        onChanged();
      }
      
      // optional int32 luckDrawNum = 7;
      private int luckDrawNum_ ;
      public boolean hasLuckDrawNum() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getLuckDrawNum() {
        return luckDrawNum_;
      }
      public Builder setLuckDrawNum(int value) {
        bitField0_ |= 0x00000040;
        luckDrawNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearLuckDrawNum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        luckDrawNum_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:buffer.GCGetLuckDrawInfoProto)
    }
    
    static {
      defaultInstance = new GCGetLuckDrawInfoProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buffer.GCGetLuckDrawInfoProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buffer_GCGetLuckDrawInfoProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buffer_GCGetLuckDrawInfoProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032GCGetLuckDrawInfoMsg.proto\022\006buffer\"\235\001\n" +
      "\026GCGetLuckDrawInfoProto\022\025\n\007msgType\030\001 \001(\005" +
      ":\0043316\022\016\n\006status\030\002 \001(\005\022\017\n\007luckNum\030\003 \001(\005\022" +
      "\024\n\014nextFreeTime\030\004 \001(\003\022\022\n\nmaxLuckNum\030\005 \001(" +
      "\005\022\014\n\004cost\030\006 \001(\t\022\023\n\013luckDrawNum\030\007 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_buffer_GCGetLuckDrawInfoProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_buffer_GCGetLuckDrawInfoProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buffer_GCGetLuckDrawInfoProto_descriptor,
              new java.lang.String[] { "MsgType", "Status", "LuckNum", "NextFreeTime", "MaxLuckNum", "Cost", "LuckDrawNum", },
              buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto.class,
              buffer.GCGetLuckDrawInfoMsg.GCGetLuckDrawInfoProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
