// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GCPushPaySuccessMsg.proto

package buffer;

public final class GCPushPaySuccessMsg {
  private GCPushPaySuccessMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GCPushPaySuccessProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 msgType = 1 [default = 4403];
    boolean hasMsgType();
    int getMsgType();
    
    // optional int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // optional int32 id = 3;
    boolean hasId();
    int getId();
    
    // optional int32 blueCashNum = 4;
    boolean hasBlueCashNum();
    int getBlueCashNum();
    
    // optional int32 rewardBlueCashNum = 5;
    boolean hasRewardBlueCashNum();
    int getRewardBlueCashNum();
    
    // optional string items = 6;
    boolean hasItems();
    String getItems();
  }
  public static final class GCPushPaySuccessProto extends
      com.google.protobuf.GeneratedMessage
      implements GCPushPaySuccessProtoOrBuilder {
    // Use GCPushPaySuccessProto.newBuilder() to construct.
    private GCPushPaySuccessProto(Builder builder) {
      super(builder);
    }
    private GCPushPaySuccessProto(boolean noInit) {}
    
    private static final GCPushPaySuccessProto defaultInstance;
    public static GCPushPaySuccessProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public GCPushPaySuccessProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffer.GCPushPaySuccessMsg.internal_static_buffer_GCPushPaySuccessProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffer.GCPushPaySuccessMsg.internal_static_buffer_GCPushPaySuccessProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 msgType = 1 [default = 4403];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional int32 id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getId() {
      return id_;
    }
    
    // optional int32 blueCashNum = 4;
    public static final int BLUECASHNUM_FIELD_NUMBER = 4;
    private int blueCashNum_;
    public boolean hasBlueCashNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getBlueCashNum() {
      return blueCashNum_;
    }
    
    // optional int32 rewardBlueCashNum = 5;
    public static final int REWARDBLUECASHNUM_FIELD_NUMBER = 5;
    private int rewardBlueCashNum_;
    public boolean hasRewardBlueCashNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getRewardBlueCashNum() {
      return rewardBlueCashNum_;
    }
    
    // optional string items = 6;
    public static final int ITEMS_FIELD_NUMBER = 6;
    private java.lang.Object items_;
    public boolean hasItems() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getItems() {
      java.lang.Object ref = items_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          items_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getItemsBytes() {
      java.lang.Object ref = items_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        items_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      msgType_ = 4403;
      status_ = 0;
      id_ = 0;
      blueCashNum_ = 0;
      rewardBlueCashNum_ = 0;
      items_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, blueCashNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, rewardBlueCashNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getItemsBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, blueCashNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, rewardBlueCashNum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getItemsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements buffer.GCPushPaySuccessMsg.GCPushPaySuccessProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffer.GCPushPaySuccessMsg.internal_static_buffer_GCPushPaySuccessProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffer.GCPushPaySuccessMsg.internal_static_buffer_GCPushPaySuccessProto_fieldAccessorTable;
      }
      
      // Construct using buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = 4403;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        blueCashNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        rewardBlueCashNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        items_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto.getDescriptor();
      }
      
      public buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto getDefaultInstanceForType() {
        return buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto.getDefaultInstance();
      }
      
      public buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto build() {
        buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto buildPartial() {
        buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto result = new buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.blueCashNum_ = blueCashNum_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.rewardBlueCashNum_ = rewardBlueCashNum_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.items_ = items_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto) {
          return mergeFrom((buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto other) {
        if (other == buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasBlueCashNum()) {
          setBlueCashNum(other.getBlueCashNum());
        }
        if (other.hasRewardBlueCashNum()) {
          setRewardBlueCashNum(other.getRewardBlueCashNum());
        }
        if (other.hasItems()) {
          setItems(other.getItems());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              blueCashNum_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              rewardBlueCashNum_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              items_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 msgType = 1 [default = 4403];
      private int msgType_ = 4403;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 4403;
        onChanged();
        return this;
      }
      
      // optional int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 id = 3;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 blueCashNum = 4;
      private int blueCashNum_ ;
      public boolean hasBlueCashNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getBlueCashNum() {
        return blueCashNum_;
      }
      public Builder setBlueCashNum(int value) {
        bitField0_ |= 0x00000008;
        blueCashNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearBlueCashNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        blueCashNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 rewardBlueCashNum = 5;
      private int rewardBlueCashNum_ ;
      public boolean hasRewardBlueCashNum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getRewardBlueCashNum() {
        return rewardBlueCashNum_;
      }
      public Builder setRewardBlueCashNum(int value) {
        bitField0_ |= 0x00000010;
        rewardBlueCashNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearRewardBlueCashNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rewardBlueCashNum_ = 0;
        onChanged();
        return this;
      }
      
      // optional string items = 6;
      private java.lang.Object items_ = "";
      public boolean hasItems() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getItems() {
        java.lang.Object ref = items_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          items_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setItems(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        items_ = value;
        onChanged();
        return this;
      }
      public Builder clearItems() {
        bitField0_ = (bitField0_ & ~0x00000020);
        items_ = getDefaultInstance().getItems();
        onChanged();
        return this;
      }
      void setItems(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        items_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:buffer.GCPushPaySuccessProto)
    }
    
    static {
      defaultInstance = new GCPushPaySuccessProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buffer.GCPushPaySuccessProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buffer_GCPushPaySuccessProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buffer_GCPushPaySuccessProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031GCPushPaySuccessMsg.proto\022\006buffer\"\211\001\n\025" +
      "GCPushPaySuccessProto\022\025\n\007msgType\030\001 \001(\005:\004" +
      "4403\022\016\n\006status\030\002 \001(\005\022\n\n\002id\030\003 \001(\005\022\023\n\013blue" +
      "CashNum\030\004 \001(\005\022\031\n\021rewardBlueCashNum\030\005 \001(\005" +
      "\022\r\n\005items\030\006 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_buffer_GCPushPaySuccessProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_buffer_GCPushPaySuccessProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buffer_GCPushPaySuccessProto_descriptor,
              new java.lang.String[] { "MsgType", "Status", "Id", "BlueCashNum", "RewardBlueCashNum", "Items", },
              buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto.class,
              buffer.GCPushPaySuccessMsg.GCPushPaySuccessProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
