// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GCSendFriendShipMsg.proto

package buffer;

public final class GCSendFriendShipMsg {
  private GCSendFriendShipMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GCSendFriendShipProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 msgType = 1 [default = 2021];
    boolean hasMsgType();
    int getMsgType();
    
    // optional int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // optional int32 friendShip = 3;
    boolean hasFriendShip();
    int getFriendShip();
    
    // optional int64 targetUid = 4;
    boolean hasTargetUid();
    long getTargetUid();
    
    // optional int32 hasSendFriendShip = 5;
    boolean hasHasSendFriendShip();
    int getHasSendFriendShip();
    
    // optional int32 canReceiveFriendShip = 6;
    boolean hasCanReceiveFriendShip();
    int getCanReceiveFriendShip();
  }
  public static final class GCSendFriendShipProto extends
      com.google.protobuf.GeneratedMessage
      implements GCSendFriendShipProtoOrBuilder {
    // Use GCSendFriendShipProto.newBuilder() to construct.
    private GCSendFriendShipProto(Builder builder) {
      super(builder);
    }
    private GCSendFriendShipProto(boolean noInit) {}
    
    private static final GCSendFriendShipProto defaultInstance;
    public static GCSendFriendShipProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public GCSendFriendShipProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return buffer.GCSendFriendShipMsg.internal_static_buffer_GCSendFriendShipProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return buffer.GCSendFriendShipMsg.internal_static_buffer_GCSendFriendShipProto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 msgType = 1 [default = 2021];
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMsgType() {
      return msgType_;
    }
    
    // optional int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // optional int32 friendShip = 3;
    public static final int FRIENDSHIP_FIELD_NUMBER = 3;
    private int friendShip_;
    public boolean hasFriendShip() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getFriendShip() {
      return friendShip_;
    }
    
    // optional int64 targetUid = 4;
    public static final int TARGETUID_FIELD_NUMBER = 4;
    private long targetUid_;
    public boolean hasTargetUid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTargetUid() {
      return targetUid_;
    }
    
    // optional int32 hasSendFriendShip = 5;
    public static final int HASSENDFRIENDSHIP_FIELD_NUMBER = 5;
    private int hasSendFriendShip_;
    public boolean hasHasSendFriendShip() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getHasSendFriendShip() {
      return hasSendFriendShip_;
    }
    
    // optional int32 canReceiveFriendShip = 6;
    public static final int CANRECEIVEFRIENDSHIP_FIELD_NUMBER = 6;
    private int canReceiveFriendShip_;
    public boolean hasCanReceiveFriendShip() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getCanReceiveFriendShip() {
      return canReceiveFriendShip_;
    }
    
    private void initFields() {
      msgType_ = 2021;
      status_ = 0;
      friendShip_ = 0;
      targetUid_ = 0L;
      hasSendFriendShip_ = 0;
      canReceiveFriendShip_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, friendShip_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, targetUid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, hasSendFriendShip_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, canReceiveFriendShip_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, friendShip_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, targetUid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, hasSendFriendShip_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, canReceiveFriendShip_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static buffer.GCSendFriendShipMsg.GCSendFriendShipProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(buffer.GCSendFriendShipMsg.GCSendFriendShipProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements buffer.GCSendFriendShipMsg.GCSendFriendShipProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return buffer.GCSendFriendShipMsg.internal_static_buffer_GCSendFriendShipProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return buffer.GCSendFriendShipMsg.internal_static_buffer_GCSendFriendShipProto_fieldAccessorTable;
      }
      
      // Construct using buffer.GCSendFriendShipMsg.GCSendFriendShipProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = 2021;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        friendShip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        targetUid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        hasSendFriendShip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        canReceiveFriendShip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return buffer.GCSendFriendShipMsg.GCSendFriendShipProto.getDescriptor();
      }
      
      public buffer.GCSendFriendShipMsg.GCSendFriendShipProto getDefaultInstanceForType() {
        return buffer.GCSendFriendShipMsg.GCSendFriendShipProto.getDefaultInstance();
      }
      
      public buffer.GCSendFriendShipMsg.GCSendFriendShipProto build() {
        buffer.GCSendFriendShipMsg.GCSendFriendShipProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private buffer.GCSendFriendShipMsg.GCSendFriendShipProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        buffer.GCSendFriendShipMsg.GCSendFriendShipProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public buffer.GCSendFriendShipMsg.GCSendFriendShipProto buildPartial() {
        buffer.GCSendFriendShipMsg.GCSendFriendShipProto result = new buffer.GCSendFriendShipMsg.GCSendFriendShipProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.friendShip_ = friendShip_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.targetUid_ = targetUid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hasSendFriendShip_ = hasSendFriendShip_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.canReceiveFriendShip_ = canReceiveFriendShip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof buffer.GCSendFriendShipMsg.GCSendFriendShipProto) {
          return mergeFrom((buffer.GCSendFriendShipMsg.GCSendFriendShipProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(buffer.GCSendFriendShipMsg.GCSendFriendShipProto other) {
        if (other == buffer.GCSendFriendShipMsg.GCSendFriendShipProto.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasFriendShip()) {
          setFriendShip(other.getFriendShip());
        }
        if (other.hasTargetUid()) {
          setTargetUid(other.getTargetUid());
        }
        if (other.hasHasSendFriendShip()) {
          setHasSendFriendShip(other.getHasSendFriendShip());
        }
        if (other.hasCanReceiveFriendShip()) {
          setCanReceiveFriendShip(other.getCanReceiveFriendShip());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              friendShip_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              targetUid_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              hasSendFriendShip_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              canReceiveFriendShip_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 msgType = 1 [default = 2021];
      private int msgType_ = 2021;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 2021;
        onChanged();
        return this;
      }
      
      // optional int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 friendShip = 3;
      private int friendShip_ ;
      public boolean hasFriendShip() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getFriendShip() {
        return friendShip_;
      }
      public Builder setFriendShip(int value) {
        bitField0_ |= 0x00000004;
        friendShip_ = value;
        onChanged();
        return this;
      }
      public Builder clearFriendShip() {
        bitField0_ = (bitField0_ & ~0x00000004);
        friendShip_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 targetUid = 4;
      private long targetUid_ ;
      public boolean hasTargetUid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTargetUid() {
        return targetUid_;
      }
      public Builder setTargetUid(long value) {
        bitField0_ |= 0x00000008;
        targetUid_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetUid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetUid_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 hasSendFriendShip = 5;
      private int hasSendFriendShip_ ;
      public boolean hasHasSendFriendShip() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getHasSendFriendShip() {
        return hasSendFriendShip_;
      }
      public Builder setHasSendFriendShip(int value) {
        bitField0_ |= 0x00000010;
        hasSendFriendShip_ = value;
        onChanged();
        return this;
      }
      public Builder clearHasSendFriendShip() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hasSendFriendShip_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 canReceiveFriendShip = 6;
      private int canReceiveFriendShip_ ;
      public boolean hasCanReceiveFriendShip() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getCanReceiveFriendShip() {
        return canReceiveFriendShip_;
      }
      public Builder setCanReceiveFriendShip(int value) {
        bitField0_ |= 0x00000020;
        canReceiveFriendShip_ = value;
        onChanged();
        return this;
      }
      public Builder clearCanReceiveFriendShip() {
        bitField0_ = (bitField0_ & ~0x00000020);
        canReceiveFriendShip_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:buffer.GCSendFriendShipProto)
    }
    
    static {
      defaultInstance = new GCSendFriendShipProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:buffer.GCSendFriendShipProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_buffer_GCSendFriendShipProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_buffer_GCSendFriendShipProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031GCSendFriendShipMsg.proto\022\006buffer\"\236\001\n\025" +
      "GCSendFriendShipProto\022\025\n\007msgType\030\001 \001(\005:\004" +
      "2021\022\016\n\006status\030\002 \001(\005\022\022\n\nfriendShip\030\003 \001(\005" +
      "\022\021\n\ttargetUid\030\004 \001(\003\022\031\n\021hasSendFriendShip" +
      "\030\005 \001(\005\022\034\n\024canReceiveFriendShip\030\006 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_buffer_GCSendFriendShipProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_buffer_GCSendFriendShipProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_buffer_GCSendFriendShipProto_descriptor,
              new java.lang.String[] { "MsgType", "Status", "FriendShip", "TargetUid", "HasSendFriendShip", "CanReceiveFriendShip", },
              buffer.GCSendFriendShipMsg.GCSendFriendShipProto.class,
              buffer.GCSendFriendShipMsg.GCSendFriendShipProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
